### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by eerolasi** [ksuominen/scientific-calculator#1]
Kloonasin projektin sunnuntaina klo. 22

Projekti on jo viimeistelyä vaille valmis.

Laskin toimii odotetulla tavalla myös virhetilanteissa. Virheidenkäsittely on hyvin kattavaa. En löytänyt tilannetta, jossa virheellinen syöte ei antaisi käyttäjäystävällistä virheilmoitusta. Testit ovat monipuoliset ja menevät läpi.

Parannettavaa koodin toiminnallisuuteen en keksi, mutta jonkin tyylitarkastuksen kuten pylintin avulla koodin laatua voisi siistiä/selkeyttää.
Koodi on jo hyvin dokumentoitua docstringein, mutta joissain luokissa sitä voisi vielä lisätä.

Käyttöliittymää ei kai pitänyt arvoida, mutta ikkunan kokoa voisi vähän suurentaa, jotta oikealla olevat napit mahtuisivat kokonaan sen sisään.
![image](https://github.com/ksuominen/scientific-calculator/assets/93593718/a401ea9c-f800-4a0e-90e4-da6840a2206c)

Laskin on todella monipuolinen toiminnallisuuksiltaan ja oikeastaan valmis, hyvää työtä!

**Comment by ksuominen** [comment]
Kiitos palautteesta! :) Ja tuo käyttöliittymäkommentti & -kuva oli tosi hyödylliset, itsellä on windows ja nappulat mahtuivat ihan ok, mutta muokkasin nyt vähän lisää että toimisi toivottavasti jatkossa niin että nappulat mahtuu muillakin käyttiksillä.
