### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by Robomarti** [ksuominen/scientific-calculator#2]
24.08.2023, 17:30

- Sovellus voisi "autocomplete" kaikki sulkemattomat sulkeet kiinni kun painaa "=" -nappia.
- En pystynyt skaalaamaan ikkunaa, joten piti katsoa toiselta näytöltä GUI- kuvaa referenssinä, sillä viimeisen sarakkeen napit näkyi alle puoliksi, mutta onneksi edes sen verran että sain painettua
- Sovellus voisi edes joissain tapauksissa selittää, että mikä aiheutti syntaksivirheen.
- Testausdokumentaatiossa mainittu komento "poetry run invoke coverage_report" ei tee mitään, vaan se pitäisi muuttaa "poetry run invoke coverage-report".

+ Monipuolisesti eri laskutoimintoja suoritettu, yleisesti oikein hyvä laskin, kunhan sitä olisi helpompi käyttää (esim. just näkemällä mitä napeissa lukee). Yleisesti näyttää aika valmiilta projektilta.
+ Testaus on hyvää ja kattavaa.

**Comment by ksuominen** [comment]
Kiitos palautteesta! :) Saan tästä hyviä ideoita jatkokehitysehdotuksiin. Tuo nappuloiden mahtumattomuus tuli ilmi myös edellisestä vertaispalautteesta, yritin nyt muokata käyttöliittymää että toimisi paremmin. Tkinter on uusi tuttavuus, ja ei vaikuta maailman näppärimmältä tavalta määritellä asioiden kokoja ja sijoitteluja. Itselläni on windows, ja nappulat mahtuivat ihan jees, joten oli tosi hyvä saada näitä palautteita että muilla käyttiksillä ei toimi samalla lailla. Tuo typo testausdokumentaatiossa pitää myös korjata, hyvä kun huomasit sen!

**Comment by Robomarti** [comment]
Itse käytin kali linuxia arviointiin, sillä ei näistä töistä koskaan tiedä mitkä toimii windowsilla myös ja mitkä ei. Katsoin myös sen toisen issuen, ja sekin varmaan käytti linuxia sitten. Jos sinulla ei ole linuxia niin kantsii ladata virtualbox tai joku toinen virtuaalikone että pääset testaamaan, sillä kurssin arvosana tulee kuitenkin opettajien linuxilla testaamisista.
